command! -nargs=+ -bar Load call unpack#load(<args>)
command! -nargs=0 -bar UnpackClean call unpack#clean()
command! -nargs=0 -bar UnpackCompile call unpack#compile()
command! -nargs=0 -bar UnpackInstall call unpack#install()
command! -nargs=0 -bar UnpackUpdate call unpack#update()
